<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
      <_ContentIncludedByDefault Remove="Pages\Error.cshtml" />
      <_ContentIncludedByDefault Remove="Pages\Index.cshtml" />
      <_ContentIncludedByDefault Remove="Pages\Privacy.cshtml" />
      <_ContentIncludedByDefault Remove="Pages\Shared\_Layout.cshtml" />
      <_ContentIncludedByDefault Remove="Pages\Shared\_ValidationScriptsPartial.cshtml" />
      <_ContentIncludedByDefault Remove="Pages\_ViewImports.cshtml" />
      <_ContentIncludedByDefault Remove="Pages\_ViewStart.cshtml" />
    </ItemGroup>

    <ItemGroup>
      <Reference Include="Entities.Common">
        <HintPath>..\..\..\Dlls\Common\Entities.Common.dll</HintPath>
      </Reference>
      <Reference Include="Persistence.Common">
        <HintPath>..\..\..\Dlls\Common\Persistence.Common.dll</HintPath>
      </Reference>
      <Reference Include="Services.Common">
        <HintPath>..\..\..\Dlls\Common\Services.Common.dll</HintPath>
      </Reference>
      <Reference Include="Web.Common">
        <HintPath>..\..\..\Dlls\Common\Web.Common.dll</HintPath>
      </Reference>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Entities\Entities.csproj" />
      <ProjectReference Include="..\Persistence\Persistence.csproj" />
      <ProjectReference Include="..\Services\Services.csproj" />
      <ProjectReference Include="..\Web\Web.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="wwwroot\menu\categories\" />
      <Folder Include="wwwroot\menu\items\" />
      <Folder Include="wwwroot\menu\subCategories\" />
    </ItemGroup>

</Project>
